-- ============================================================
-- Normattiva — Seed dati: tutte le norme senza embedding
-- Gli embedding vengono aggiunti dallo script Python ingest_norme.py
-- Esegui nel SQL Editor di Supabase DOPO schema.sql
-- ============================================================

insert into norme (norma_id, titolo, estremi, descrizione, articoli_chiave, tags, url_normattiva, url_ricerca, convenzione_only)
values

('dlgs_36_2023',
 'Codice dei contratti pubblici',
 'D.Lgs. 31 marzo 2023, n. 36',
 'Disciplina l''affidamento e l''esecuzione di appalti pubblici e concessioni. Regolamenta le soglie per affidamento diretto (art. 50), procedura negoziata (art. 72) e procedura aperta (art. 71). Obbliga alla nomina del RUP e all''acquisizione del CIG.',
 array['art. 50 — affidamento diretto','art. 51 — procedura negoziata semplificata','art. 71 — procedura aperta','art. 72 — procedura negoziata','art. 15 — RUP'],
 array['acquisto','appalto','gara','fornitore','mepa','consip','lavori','servizi','manutenzione','hardware','software','cloud','determina','cig','cup','rup'],
 'https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2023-03-31;36',
 'https://www.normattiva.it/ricerca/semplice?query=decreto+legislativo+36+2023+codice+contratti+pubblici',
 false),

('dlgs_82_2005',
 'Codice dell''Amministrazione Digitale (CAD)',
 'D.Lgs. 7 marzo 2005, n. 82',
 'Regola la digitalizzazione della PA, l''uso di software, cloud computing e servizi ICT. Stabilisce l''obbligo di preferenza per soluzioni open source (art. 68) e il riuso del software (art. 69).',
 array['art. 68 — analisi comparativa soluzioni','art. 69 — riuso del software','art. 50 — disponibilità dei dati'],
 array['software','cloud','digitalizzazione','ict','dati','agid','open-source','riuso'],
 'https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2005-03-07;82',
 'https://www.normattiva.it/ricerca/semplice?query=codice+amministrazione+digitale+CAD+82+2005',
 false),

('dlgs_33_2013',
 'Trasparenza e accesso civico',
 'D.Lgs. 14 marzo 2013, n. 33',
 'Obbliga le PA alla pubblicazione su ''Amministrazione Trasparente'' di dati su contratti, affidamenti e spese. Ogni determina di acquisto rilevante deve essere pubblicata. Disciplina anche il FOIA (art. 5).',
 array['art. 23 — obblighi pubblicazione provvedimenti','art. 37 — pubblicazione contratti e appalti','art. 5 — accesso civico'],
 array['trasparenza','anticorruzione','foia','pubblicazione','accesso','determina'],
 'https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2013-03-14;33',
 'https://www.normattiva.it/ricerca/semplice?query=decreto+legislativo+33+2013+trasparenza+amministrativa',
 false),

('l_190_2012',
 'Legge Anticorruzione',
 'L. 6 novembre 2012, n. 190',
 'Introduce misure per la prevenzione della corruzione nella PA. Obbliga gli enti al PTPCT. L''art. 1 co. 41 richiede l''attestazione di assenza di conflitto d''interessi in ogni provvedimento.',
 array['art. 1 — PTPCT','art. 1 co. 9 — misure obbligatorie','art. 1 co. 41 — conflitto d''interessi'],
 array['anticorruzione','trasparenza','conflitto','ptpct','corruzione'],
 'https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:legge:2012-11-06;190',
 'https://www.normattiva.it/ricerca/semplice?query=legge+190+2012+anticorruzione',
 false),

('dlgs_267_2000',
 'Testo Unico Enti Locali (TUEL)',
 'D.Lgs. 18 agosto 2000, n. 267',
 'Disciplina l''organizzazione di Comuni e Province. Regolamenta competenze degli organi, forma degli atti (delibere, determine) e gestione finanziaria. Riferimento primario per ogni atto amministrativo di ente locale.',
 array['art. 107 — competenze dirigenziali','art. 192 — determinazione a contrarre','art. 183 — assunzione impegno di spesa'],
 array['comune','provincia','delibera','ordinanza','bilancio','determina','ente-locale','dirigente'],
 'https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2000-08-18;267',
 'https://www.normattiva.it/ricerca/semplice?query=testo+unico+enti+locali+TUEL+267+2000',
 false),

('dlgs_165_2001',
 'Testo Unico Pubblico Impiego (TUPI)',
 'D.Lgs. 30 marzo 2001, n. 165',
 'Disciplina il rapporto di lavoro dei dipendenti PA. Regola incarichi, consulenze esterne (art. 7), formazione e organizzazione degli uffici.',
 array['art. 7 — gestione risorse e incarichi','art. 19 — incarichi dirigenziali','art. 36 — utilizzo flessibile'],
 array['personale','consulenza','formazione','incarico','dipendente','dirigente','lavoro'],
 'https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2001-03-30;165',
 'https://www.normattiva.it/ricerca/semplice?query=testo+unico+pubblico+impiego+165+2001',
 false),

('dlgs_196_2003',
 'Codice Privacy + GDPR',
 'D.Lgs. 30 giugno 2003, n. 196 (mod. dal Reg. UE 2016/679)',
 'Disciplina il trattamento dei dati personali. Il GDPR è direttamente applicabile. Rilevante per acquisti di software, cloud e qualsiasi trattamento dati personali da parte della PA.',
 array['art. 13 GDPR — informativa','art. 28 GDPR — responsabile trattamento','art. 32 GDPR — sicurezza trattamento'],
 array['privacy','dati','gdpr','trattamento','personali','software','cloud'],
 'https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2003-06-30;196',
 'https://www.normattiva.it/ricerca/semplice?query=codice+privacy+196+2003+GDPR',
 false),

('dlgs_81_2008',
 'Testo Unico Sicurezza sul Lavoro',
 'D.Lgs. 9 aprile 2008, n. 81',
 'Disciplina la sicurezza nei luoghi di lavoro. Negli appalti richiede il DUVRI e la verifica dei requisiti di sicurezza del fornitore.',
 array['art. 26 — obblighi connessi ai contratti d''appalto (DUVRI)','art. 17 — obblighi non delegabili'],
 array['sicurezza','lavori','contratto','duvri','appalto','cantiere'],
 'https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2008-04-09;81',
 'https://www.normattiva.it/ricerca/semplice?query=testo+unico+sicurezza+lavoro+81+2008',
 false),

('dlgs_118_2011',
 'Armonizzazione contabile enti locali',
 'D.Lgs. 23 giugno 2011, n. 118',
 'Disciplina i sistemi contabili e gli schemi di bilancio di Regioni, Province e Comuni. Regolamenta la corretta imputazione delle spese e gli impegni di bilancio.',
 array['art. 56 — principi contabili applicati','Allegato 4/2 — principio della competenza finanziaria'],
 array['bilancio','fondo','comune','provincia','contabilita','impegno','spesa'],
 'https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2011-06-23;118',
 'https://www.normattiva.it/ricerca/semplice?query=decreto+legislativo+118+2011+armonizzazione+contabile',
 false),

('pnrr_missione1',
 'PNRR — Missione 1: Digitalizzazione PA',
 'Piano Nazionale di Ripresa e Resilienza, Missione 1',
 'Definisce gli investimenti per la transizione digitale della PA. Gli acquisti ICT finanziati dal PNRR devono rispettare le linee guida AgID e i requisiti cloud.',
 array['Componente 1.1 — Infrastrutture digitali','Componente 1.2 — Abilitazione migrazione al cloud'],
 array['pnrr','digitalizzazione','agid','fondo','cloud','ict','transizione'],
 'https://www.normattiva.it/ricerca/semplice?query=PNRR+piano+nazionale+ripresa+resilienza+digitalizzazione',
 'https://www.normattiva.it/ricerca/semplice?query=PNRR+piano+nazionale+ripresa+resilienza+digitalizzazione',
 false),

('l_136_2010',
 'Tracciabilità dei flussi finanziari (CIG/CUP)',
 'L. 13 agosto 2010, n. 136',
 'Obbliga le stazioni appaltanti a utilizzare conti dedicati e strumenti tracciabili. Ogni contratto pubblico deve riportare il CIG e, se finanziato con fondi pubblici, il CUP.',
 array['art. 3 — obblighi di tracciabilità dei flussi finanziari','art. 3 co. 5 — obbligo CIG e CUP','art. 6 — sanzioni per violazione tracciabilità'],
 array['cig','cup','tracciabilità','rup','tracciabilita','flussi','contratto'],
 'https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:legge:2010-08-13;136',
 'https://www.normattiva.it/ricerca/semplice?query=legge+136+2010+tracciabilita+flussi+finanziari+CIG',
 false),

('l_241_1990',
 'Legge sul procedimento amministrativo',
 'L. 7 agosto 1990, n. 241',
 'Regola il procedimento amministrativo in tutte le sue fasi: avvio, istruttoria, partecipazione dei privati, motivazione degli atti, silenzio-assenso, accesso agli atti. Riferimento trasversale per la legittimità di qualsiasi provvedimento PA.',
 array['art. 1 — principi generali','art. 3 — obbligo di motivazione','art. 7 — comunicazione avvio procedimento','art. 21-octies — annullabilità','art. 22 — accesso agli atti'],
 array['procedimento','motivazione','accesso','provvedimento','determina','delibera','legittimita','silenzio'],
 'https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:legge:1990-08-07;241',
 'https://www.normattiva.it/ricerca/semplice?query=legge+241+1990+procedimento+amministrativo',
 false),

('dlgs_50_2016',
 'Codice dei contratti pubblici 2016 (previgente)',
 'D.Lgs. 18 aprile 2016, n. 50',
 'Codice appalti previgente, abrogato dal D.Lgs. 36/2023 ma ancora applicabile ai contratti aggiudicati prima del 1° luglio 2023. Rilevante per proroghe e collaudi di contratti avviati sotto la vecchia disciplina.',
 array['art. 36 — contratti sotto soglia','art. 63 — procedura negoziata senza bando','art. 95 — criteri di aggiudicazione','art. 106 — modifica dei contratti in corso'],
 array['proroga','affidamento','appalto','previgente','storico','collaudo','modifica'],
 'https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2016-04-18;50',
 'https://www.normattiva.it/ricerca/semplice?query=decreto+legislativo+50+2016+codice+contratti+pubblici',
 false),

('l_296_2006_consip',
 'Obbligo Consip / MEPA (L. Finanziaria 2007)',
 'L. 27 dicembre 2006, n. 296, art. 1 co. 449-450',
 'Obbliga le PA ad approvvigionarsi tramite convenzioni Consip o MEPA per acquisti sotto soglia. Il mancato rispetto espone il RUP a responsabilità erariale.',
 array['art. 1 co. 449 — obbligo Consip per PA statali','art. 1 co. 450 — obbligo MEPA sotto soglia','art. 1 co. 452 — benchmark prezzi Consip'],
 array['mepa','consip','benchmark','convenzione','acquisto'],
 'https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:legge:2006-12-27;296',
 'https://www.normattiva.it/ricerca/semplice?query=legge+296+2006+finanziaria+consip+mepa+449',
 true),

('dlgs_231_2001',
 'Responsabilità amministrativa degli enti (D.Lgs. 231)',
 'D.Lgs. 8 giugno 2001, n. 231',
 'Disciplina la responsabilità amministrativa delle persone giuridiche per reati commessi nell''interesse dell''ente. La PA deve verificare che il fornitore sia dotato di Modello Organizzativo 231 (MOG) per prevenire corruzione e frode.',
 array['art. 5 — responsabilità dell''ente','art. 6 — esimenti: MOG efficace','art. 24 — reati contro la PA','art. 25 — corruzione e induzione indebita'],
 array['mog','231','corruzione','fornitore','appalto','responsabilita','anticorruzione'],
 'https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2001-06-08;231',
 'https://www.normattiva.it/ricerca/semplice?query=decreto+legislativo+231+2001+responsabilita+amministrativa+enti',
 false),

('circ_agid_cloud_2021',
 'Qualificazione cloud PA — Linee guida AgID / ACN',
 'Circolare AgID n. 2/2018 + Determinazione AgID 628/2021 + Regolamento ACN 2022',
 'Definisce i requisiti di qualificazione per i servizi cloud acquistabili dalla PA. Solo i servizi nel Catalogo Cloud PA possono essere acquisiti. Classifica i servizi in PSN, Cloud qualificato, SaaS qualificato.',
 array['Determinazione 628/2021 — qualificazione SaaS','Regolamento ACN 2022 — classificazione dati cloud','Circolare AgID 2/2018 — criteri qualificazione CSP'],
 array['qualificazione','marketplace','psn','saas','agid','cloud','acn','iaas','paas'],
 'https://www.agid.gov.it/it/infrastrutture/cloud-pa',
 'https://www.normattiva.it/ricerca/semplice?query=AgID+qualificazione+cloud+PA+628+2021',
 false),

('l_328_2000',
 'Legge quadro servizi sociali',
 'L. 8 novembre 2000, n. 328',
 'Legge quadro che disciplina il sistema integrato di interventi e servizi sociali. L''art. 6 attribuisce ai Comuni le funzioni di gestione dei servizi sociali. L''art. 25 stabilisce l''ISEE come strumento di accesso alle prestazioni.',
 array['art. 6 — funzioni dei Comuni','art. 22 — sistema integrato','art. 25 — ISEE'],
 array['servizi-sociali','sociale','isee','retta','anziani','disabili','minori','assistenza','contributo','prestazione','compartecipazione','comune','welfare','bisogno','nucleo-familiare','assistente-sociale'],
 'https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:legge:2000-11-08;328',
 'https://www.normattiva.it/ricerca/semplice?query=legge+328+2000+servizi+sociali',
 false),

('dpcm_159_2013',
 'Regolamento ISEE',
 'D.P.C.M. 5 dicembre 2013, n. 159',
 'Disciplina la determinazione dell''ISEE. L''art. 6 regolamenta l''ISEE socio-sanitario per prestazioni residenziali (RSA, case di riposo, strutture per disabili), che considera anche reddito e patrimonio del coniuge e figli non conviventi.',
 array['art. 2 — ISEE ordinario','art. 6 — ISEE socio-sanitario','art. 7 — ISEE minorenni','art. 4 — nucleo familiare'],
 array['isee','isee-sociosanitario','retta','rsa','ricovero','anziani','disabili','servizi-sociali','sociale','nucleo-familiare','assistenza','prestazione','socio-sanitario','struttura-residenziale','casa-riposo'],
 'https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.del.presidente.del.consiglio.dei.ministri:2013-12-05;159',
 'https://www.normattiva.it/ricerca/semplice?query=DPCM+159+2013+ISEE+regolamento',
 false),

('l_104_1992',
 'Legge 104 — Assistenza persone con disabilità',
 'L. 5 febbraio 1992, n. 104',
 'Legge quadro sull''assistenza e l''integrazione sociale delle persone con disabilità. Attribuisce ai Comuni l''obbligo di garantire servizi di assistenza e riabilitazione. Disciplina permessi lavorativi (art. 33) e inserimento lavorativo.',
 array['art. 3 — definizione handicap grave','art. 8 — interventi dei Comuni','art. 10 — integrazione scolastica','art. 33 — agevolazioni lavorative'],
 array['disabili','handicap','disabilita','assistenza','integrazione','servizi-sociali','sociale','comune','retta','contributo','permessi','welfare','prestazione'],
 'https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:legge:1992-02-05;104',
 'https://www.normattiva.it/ricerca/semplice?query=legge+104+1992+assistenza+disabili',
 false)

on conflict (norma_id) do update set
  titolo           = excluded.titolo,
  estremi          = excluded.estremi,
  descrizione      = excluded.descrizione,
  articoli_chiave  = excluded.articoli_chiave,
  tags             = excluded.tags,
  url_normattiva   = excluded.url_normattiva,
  url_ricerca      = excluded.url_ricerca,
  convenzione_only = excluded.convenzione_only;

-- Verifica
select norma_id, titolo, array_length(tags,1) as num_tags from norme order by creato_il;
